using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Editor.NisGab
{
    internal static class InputActionGenerator
    {       
        private const string ContextMenuName = "Assets/Generate Input Action Binding";
        private const string OutputNamespace = "NisGab";


        [MenuItem(ContextMenuName)]
        public static void GenerateInputActionCode()
        {
            var selectedObject = Selection.activeObject as InputActionAsset;
            if (selectedObject == null)
            {
                Debug.LogError("Must select an InputActionAsset to generate input action code");
                return;
            }

            string assetName = Path.GetFileNameWithoutExtension(AssetDatabase.GetAssetPath(selectedObject));
            assetName = char.ToUpperInvariant(assetName[0]) + assetName[1..];
            string assetVariableName = char.ToLowerInvariant(assetName[0]) + assetName[1..];
            GenerateCodeFromAsset(selectedObject, assetName, assetVariableName);

        }

        [MenuItem(ContextMenuName, true)]
        private static bool ValidateGenerateInputActionCode()
        {
            return Selection.activeObject is InputActionAsset;
        }

        private static string CreateHeader(string assetName)
        {
            return
                "//------------------------------------------------------------------------------\n" +
                "// <auto-generated>\n" +
                "//     This code was auto-generated by NisGab's code generation tooling\n" +
                "//     from Assets/Config/" + assetName + ".inputactions\n" +
                "//\n" +
                "//     Changes to this file may cause incorrect behavior and will be lost if\n" +
                "//     the code is regenerated.\n" +
                "// </auto-generated>\n" +
                "//------------------------------------------------------------------------------\n\n\n";
        }

        private static void GenerateCodeFromAsset(InputActionAsset selectedObject, string assetName, string assetVariableName)
        {
            string targetDirectory = GetTargetDirectory(selectedObject);
            if (Directory.Exists(targetDirectory))
            {
                string[] files = Directory.GetFiles(targetDirectory, "*.*", SearchOption.AllDirectories);
                foreach (string file in files)
                {
                    File.Delete(file);
                }
            }
            
            ReadOnlyArray<InputActionMap> inputActionMaps = selectedObject.actionMaps;
            foreach (InputActionMap inputActionMap in inputActionMaps)
            {
                GenerateInputActionClass(inputActionMap, targetDirectory, assetName);
            }

            GenerateInputEventClass(inputActionMaps, targetDirectory, assetName, assetVariableName);
        }

        private static void GenerateInputEventClass(
            ReadOnlyArray<InputActionMap> inputActionMaps, string targetDirectory, string assetName, string assetVariableName)
        {
            StringBuilder sb = new();
            
            sb.Append(CreateHeader(assetName));
            sb.AppendLine("namespace " + OutputNamespace);
            sb.AppendLine("{");
            sb.AppendLine("\tpublic class EventBus : LazySingleton<EventBus>");
            sb.AppendLine("\t{");
            foreach (InputActionMap inputActionMap in inputActionMaps)
            {
                string mapName = inputActionMap.name;
                sb.AppendLine("\t\tpublic static " + mapName + "InputActions " + mapName + " { get; private set; } = new();");
            }

            sb.AppendLine("");
            sb.AppendLine("\t\tprivate " + assetName + " _" + assetVariableName + ";");
            sb.AppendLine("");
            sb.AppendLine("\t\tprotected override void Awake()");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tbase.Awake();");
            sb.AppendLine("\t\t\tInitializeInternal();");
            sb.AppendLine("\t\t\tUnityEngine.Application.quitting += OnApplicationQuit;");
            sb.AppendLine("\t\t}");
            sb.AppendLine("");
            sb.AppendLine("\t\tprivate void OnDestroy()");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tUnInitialize();");
            sb.AppendLine("\t\t}");
            sb.AppendLine("");
            sb.AppendLine("\t\tpublic static void Initialize()");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tvar _ = Instance;");
            sb.AppendLine("\t\t}");
            sb.AppendLine("");

            foreach (InputActionMap inputActionMap in inputActionMaps)
            {
                string mapName = inputActionMap.name;
                sb.AppendLine("\t\tpublic static bool Enable" + mapName + "Input()");
                sb.AppendLine("\t\t{");
                sb.AppendLine("\t\t\tif (!IsValid()) { return false; }");
                sb.AppendLine("\t\t\tif (Instance._" + assetVariableName + "." + mapName + ".enabled) { return false; }");
                sb.AppendLine("\t\t\t");
                sb.AppendLine("\t\t\tInstance._" + assetVariableName + "." + mapName + ".Enable();");
                sb.AppendLine("\t\t\treturn true;");
                sb.AppendLine("\t\t}");
                sb.AppendLine("");
                sb.AppendLine("\t\tpublic static bool Disable" + mapName + "Input()");
                sb.AppendLine("\t\t{");
                sb.AppendLine("\t\t\tif (!IsValid()) { return false; }");
                sb.AppendLine("\t\t\tif (!Instance._" + assetVariableName + "." + mapName + ".enabled) { return false; }");
                sb.AppendLine("\t\t\t");
                sb.AppendLine("\t\t\tInstance._" + assetVariableName + "." + mapName + ".Disable();");
                sb.AppendLine("\t\t\treturn true;");
                sb.AppendLine("\t\t}");
                sb.AppendLine("");
            }

            sb.AppendLine("\t\tprivate void InitializeInternal()");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tDontDestroyOnLoad(gameObject);");
            sb.AppendLine("\t\t\t_" + assetVariableName + " = new " + assetName + "();");
            foreach (InputActionMap inputActionMap in inputActionMaps)
            {
                string mapName = inputActionMap.name;
                sb.AppendLine("\t\t\t" + mapName + ".Bind(_" + assetVariableName + "." + mapName + ");");
            }

            sb.AppendLine("\t\t}");
            sb.AppendLine("");
            sb.AppendLine("\t\tprivate void UnInitialize()");
            sb.AppendLine("\t\t{");
            sb.AppendLine("\t\t\tif (_" + assetVariableName + " == null) { return; }");
            foreach (InputActionMap inputActionMap in inputActionMaps)
            {
                string mapName = inputActionMap.name;
                sb.AppendLine("\t\t\t" + mapName + ".UnBind(_" + assetVariableName + "." + mapName + ");");
            }

            sb.AppendLine("\t\t}");
            sb.AppendLine("\t}");
            sb.Append("}");

            if (!Directory.Exists(targetDirectory)) { Directory.CreateDirectory(targetDirectory); }

            string filePath = Path.Combine(targetDirectory, "EventBus.cs");

            File.WriteAllText(filePath, sb.ToString().Replace("\r\n", "\n"), Encoding.UTF8);
            AssetDatabase.Refresh();
        }

        private static void GenerateInputActionClass(InputActionMap inputActionMap, string targetDirectory, string assetName)
        {
            string mapName = inputActionMap.name;
            string classString = GenerateClassString(inputActionMap, assetName);
            string filePath = Path.Combine(targetDirectory, mapName + "Inputactions.cs");
            if (!Directory.Exists(targetDirectory)) { Directory.CreateDirectory(targetDirectory); }

            File.WriteAllText(filePath, classString.Replace("\r\n", "\n"), Encoding.UTF8);
            AssetDatabase.Refresh();
        }

        private static string GenerateClassString(InputActionMap inputActionMap, string assetName)
        {
            string mapName = inputActionMap.name;
            ReadOnlyArray<InputAction> actions = inputActionMap.actions;
            StringBuilder sb = new();
            sb.Append(CreateHeader(assetName));
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine.InputSystem;\n");
            sb.AppendLine("namespace " + OutputNamespace);
            sb.AppendLine("{");
            sb.AppendLine("\t/// <summary>");
            sb.AppendLine("\t/// Simple event container for " + mapName + " actions");
            sb.AppendLine("\t/// </summary>");
            sb.AppendLine("\tpublic class " + mapName + "InputActions");
            sb.AppendLine("\t{");

            foreach (InputAction action in actions)
            {
                sb.AppendLine("\t\tpublic event Action<InputAction.CallbackContext> " + action.name + ";");
            }

            sb.AppendLine("");
            sb.AppendLine("\t\tinternal void Bind(" + assetName + "." + mapName + "Actions actions)");
            sb.AppendLine("\t\t{");

            foreach (string actionName in actions.Select(action => action.name))
            {
                sb.AppendLine("\t\t\tactions." + actionName + ".performed += On" + actionName + ";");
            }

            sb.AppendLine("\t\t}");
            sb.AppendLine("");
            sb.AppendLine("\t\tinternal void UnBind(" + assetName + "." + mapName + "Actions actions)");
            sb.AppendLine("\t\t{");

            foreach (InputAction action in actions)
            {
                string actionName = action.name;
                sb.AppendLine("\t\t\tactions." + actionName + ".performed -= On" + actionName + ";");
            }

            sb.AppendLine("\t\t}");

            foreach (InputAction action in actions)
            {
                string actionName = action.name;
                sb.AppendLine("");
                sb.AppendLine("\t\tprivate void On" + actionName + "(InputAction.CallbackContext context)");
                sb.AppendLine("\t\t{");
                sb.AppendLine("\t\t\t" + actionName + "?.Invoke(context);");
                sb.AppendLine("\t\t}");
            }

            sb.AppendLine("\t}");
            sb.Append("}");

            return sb.ToString();
        }

        private static string GetTargetDirectory(InputActionAsset selectedObject)
        {
            Debug.Assert(selectedObject != null, "Selected InputActionAsset is null.");
            string assetPath = AssetDatabase.GetAssetPath(selectedObject);
            Debug.Assert(!string.IsNullOrEmpty(assetPath), "Could not find asset path for the selected InputActionAsset.");
            string directory = Path.GetDirectoryName(assetPath);
            Debug.Assert(!string.IsNullOrEmpty(directory), "Could not determine directory for the selected InputActionAsset.");
            Debug.Log("Generated files in directory: " + Path.Combine(directory, "Scripts", "Generated"));
            return Path.Combine(directory, "Generated");
        }
    }
}